com:
  dolphintwo:
    demo:
      title: Just for development
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:33306/demo
    username: root
    password: 888888
  redis:
    database: 2
    host: 127.0.0.1
    port: 36379
    password:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
server:
  port: 1111
