author:
  name: dd
  age: 28
com:
  dolphintwo:
    demo:
      title: Just for development
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:33306/demo
    username: root
    password: 888888
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update
  redis:
    database: 2
    host: 127.0.0.1
    port: 36379
    password:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/demo
server:
  port: 1111
  context-path:
